export const GET_APPLICATIONS = 'GET_APPLICATIONS'
export const SET_APPLICATIONS = 'SET_APPLICATIONS'
export const SET_CURRENT_APPLICATION = 'SET_CURRENT_APPLICATION'
export const SET_CURRENT_MODEL = 'SET_CURRENT_MODEL'